project:
  type: website
  output-dir: docs

website:
  title: "Margaret Lea Robinson"
  navbar:
    left:
      - href: index.md
        text: Home
      - href: research.md
        text: Research & Publications
      - href: computational.md
        text: Computational & Apps
      - href: teaching.md
        text: Teaching & Leadership
    right:
      - icon: github
        href: https://github.com/mlr121
      - icon: envelope
        href: mailto:mlrobinson3@wisc.edu

format:
  html:
    theme: cosmo
    toc: true
